version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo
    command:
      [
        '--replSet',
        'rs0',
        '--bind_ip_all',
        '--port',
        '27017',
        '--keyFile',
        '/etc/mongodb/pki/mongo.key',
      ]
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/key/mongo.key:/etc/mongodb/pki/mongo.key
      - 'mongo1_data:/data/db'
      - 'mongo1_config:/data/configdb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo2:
    image: mongo
    container_name: mongo2
    command:
      [
        '--replSet',
        'rs0',
        '--bind_ip_all',
        '--keyFile',
        '/etc/mongodb/pki/mongo.key',
      ]
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ${PWD}/key/mongo.key:/etc/mongodb/pki/mongo.key
      - 'mongo2_data:/data/db'
      - 'mongo2_config:/data/configdb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo3:
    image: mongo
    container_name: mongo3
    command:
      [
        '--replSet',
        'rs0',
        '--bind_ip_all',
        '--keyFile',
        '/etc/mongodb/pki/mongo.key',
      ]
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ${PWD}/key/mongo.key:/etc/mongodb/pki/mongo.key
      - 'mongo3_data:/data/db'
      - 'mongo3_config:/data/configdb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    env_file:
      - .env

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:
